title: Gogling
email: nickolay02@inbox.ru
description: Just HTTP-server written in Go and with Lua VM
baseurl: "/gogling"
url: "https://handicraftsman.github.io"
github_username: handicraftsman

gems:
 - jekyll-coffeescript
 - jekyll-sass-converter
sass:
    style: compressed
markdown: kramdown
